updated codes based on reviews
xworkzodc/mailApp pull request #2
Opened 2020-07-10 12:29 UTC by vinay-coder1

2020-07-10 13:25 UTC, xworkzodc requested changes

2020-07-10 13:25 UTC, xworkzodc commented on pom.xml
> +	<groupId>com.x-workz</groupId>
com.xworkz

2020-07-10 13:25 UTC, xworkzodc commented on pom.xml
> +			<version>${javax.servlet.version}</version>
change to javax.jstl.version

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/controller/LoginController.java
> +@Getter
remove @Getter @Setter for Controller's

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/service/SMSService.java
> +@Getter
remove @Getter and @Setter from all classes , except entity, dto ......we dont need in service, controller or dao's

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/service/OkHttpClientService.java
>  public class OkHttpClientService {
Add Interface for All services and Implement It...

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/controller/MailController.java
>  	@Value("${fromName}")
where are this properties used?

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/controller/MailController.java
>  	private XworkzService xworkzService;
Should be interface references...class cannot have another class reference.Write interface's for all services

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/dao/LoginControllerDAOImpl.java
> +	public static Logger getLogger() {
remove get and set for logger's in call classes

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/dao/LoginControllerDAOImpl.java
> +public class LoginControllerDAOImpl implements LoginControllerDAO {
You should not have DAO for generating OTP, it should be done in services...read my comments properly

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/dto/CampaignDefault.java
> -	public String getFrom_name() {
remove under_score from properties

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/dto/LoginDTO.java
> +@ToString
@Remove @ToString , this wil internally print password

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/dto/MailChimpCampaign.java
>  	List<Links> _links;
remove under_scores

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/dto/MailChimpEcommerce.java
> -	public long getTotal_orders() {
remove under scores..

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/service/LoginControllerServiceImpl.java
> +	public boolean validateAndLogin(LoginDTO dto, ModelMap model, HttpServletRequest request) {
controller cannot have ModelMap and Request...

2020-07-10 13:25 UTC, xworkzodc commented on src/main/java/com/xworkz/service/OkHttpClientService.java
> -		if (msgType == 1) {
use enum or constants instead of 1

2020-07-10 13:34 UTC, vinay-coder1 commented on src/main/java/com/xworkz/controller/LoginController.java
> +@Getter
for spring dependency injection we need setter method?

2020-07-13 11:24 UTC, ombn requested changes

2020-07-13 11:24 UTC, ombn commented on src/main/java/com/xworkz/dto/MailChimpList.java
> +	List<MailChimpMailDetails> lists;
Make properties as private

2020-07-13 11:24 UTC, ombn commented on src/main/java/com/xworkz/dto/MailChimpMailDetails.java
> -
Make properties as private in every class

2020-07-13 11:24 UTC, ombn commented on src/main/java/com/xworkz/service/LoginControllerServiceImpl.java
> +	public LocalTime mailsentTime;
properties should not be public, if public why you need getter and setter

2020-07-13 11:24 UTC, ombn commented on src/main/java/com/xworkz/service/LoginControllerServiceImpl.java
> +	public boolean validateAndLogin(LoginDTO dto, ModelMap model, HttpServletRequest request) {
still not fixed

2020-07-13 11:24 UTC, ombn commented on src/main/java/com/xworkz/service/LoginControllerServiceImpl.java
> +	public LocalTime mailsentTime;
temporaryPass, mailSentTime and loginTime should be method level

2020-07-13 11:24 UTC, ombn commented on src/main/java/com/xworkz/service/LoginServiceImpl.java
> +				String subject = toMailSubject;
Load from template(HTML file)

2020-07-13 11:24 UTC, ombn commented on src/main/webapp/css/index.css
> +	background-image: url("https://raw.githubusercontent.com/vinay-coder1/xworkz-bulk-mail-app/master/prism.png");
this should load from xworkzodc..repo

2020-07-13 13:21 UTC, vinay-coder1 commented on src/main/webapp/css/index.css
> +	background-image: url("https://raw.githubusercontent.com/vinay-coder1/xworkz-bulk-mail-app/master/prism.png");
need to make the repo public to achieve this sir

2020-07-14 12:45 UTC, vinay-coder1 commented on src/main/java/com/xworkz/service/LoginControllerServiceImpl.java
> +	public LocalTime mailsentTime;
temporaryPass, mailSentTime and loginTime , I'm accessing from two different method so I couldn't able to declare in method level sir.

2020-09-15 06:08 UTC, closed without merging